#!/bin/sh
# ~/.config/shell/profile

# defaults
export SHELL=/usr/bin/zsh
export PAGER=/usr/bin/less
if [ -n "$DISPLAY" ]; then
    export EDITOR="/usr/bin/emacsclient -q -nw"
else
    export EDITOR=/usr/bin/nvim
fi
export VISUAL="$EDITOR"
export SUDO_EDITOR=/usr/bin/nvim
export READER=/usr/bin/zathura
export TERMINAL=/usr/bin/alacritty
export COLORTERM="st-256color"
if [ -n "$DISPLAY" ]; then
    export BROWSER=/usr/bin/qutebrowser
else
    export BROWSER=/usr/bin/w3m
fi
export VIDEO=/usr/bin/mpv
export IMAGE=/usr/bin/nsxiv
export WM=/usr/local/bin/dwm

# xdg-usr-directories
userid="$(/usr/bin/id -ru)"
export XDG_DOWNLOAD_DIR="$HOME/dl"
export XDG_DOCUMENTS_DIR="$HOME/dox"
export XDG_MUSIC_DIR="$HOME/mdi/msx"
export XDG_PICTURES_DIR="$HOME/mdi/pix"
export XDG_VIDEOS_DIR="$HOME/mdi/vids"
export XDG_PROJECTS_DIR="$HOME/rsc"
export XDG_DESKTOP_DIR="$HOME/.desk"
export XDG_TEMPLATES_DIR="$HOME/.tmpl"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"
export XDG_DATA_DIRS="/usr/local/share:/usr/share:$HOME/.local/share"
export XDG_CONFIG_DIRS=/etc/xdg
export XDG_RUNTIME_DIR="/run/user/$userid"

# Video acceleration VDPAU, nouveau instead of NVIDIA
export VDPAU_DRIVER="va_gl"

# Set GTK theme for Qt
export GTK_THEME=Adwaita:dark
export GTK2_RC_FILES=/usr/share/themes/Adwaita-dark/gtk-2.0/gtkrc
#export GTK2_RC_FILES="${XDG_CONFIG_HOME:-$HOME/.config}/gtk-2.0/gtkrc"
export QT_STYLE_OVERRIDE=Adwaita-Dark

# xdg-ninja
export GNUPGHOME="${XDG_DATA_HOME:-$HOME/.local/share}/gnupg"
export ZDOTDIR="${XDG_CONFIG_HOME:-$HOME/.config}/zsh"
export W3M_DIR="${XDG_STATE_HOME:-$HOME/.local/state}/w3m"
export LYNX_CFG="${XDG_CONFIG_HOME:-$HOME/.config}/lynx/lynx.cfg"
export ANTIWORDHOME="$XDG_DOWNLOAD_DIR/antiword"
export XCURSOR_PATH="/usr/share/icons:${XDG_DATA_HOME:-$HOME/.local/share}/icons"
export ANDROID_USER_HOME="${XDG_DATA_HOME:-$HOME/.local/share}/android"
export PARALLEL_HOME="${XDG_CONFIG_HOME:-$HOME/.config}/parallel"
export INPUTRC="${XDG_CONFIG_HOME:-$HOME/.config}/readline/inputrc"
export RIPGREP_CONFIG_PATH="${XDG_CONFIG_HOME:-$HOME/.config}/ripgrep/config"
export WGETRC="${XDG_CONFIG_HOME:-$HOME/.config}/wget/wgetrc"
export FFMPEG_DATADIR="${XDG_CONFIG_HOME:-$HOME/.config}/ffmpeg"
export ASPELL_CONF="per conf ${XDG_CONFIG_HOME:-$HOME/.config}/aspell/aspell.conf; personal ${XDG_DATA_HOME:-$HOME/.local/share}/aspell/en.pws; repl ${XDG_DATA_HOME:-$HOME/.local/share}/aspell/en.prepl"
export DICTIONARY=en_GB-oxendict
# export DICPATH="${XDG_DATA_HOME:-$HOME/.local/share}/hunspell/dicts/en_GB"
dictionary_path="$(/usr/bin/find "${XDG_DATA_HOME:-$HOME/.local/share}/hunspell/dicts" \
    -mindepth 1 -type d | \
    /usr/bin/paste -sd ':' -)"
export DICPATH="$dictionary_path"
export WORDLIST="${XDG_DATA_HOME:-$HOME/.local/share}/wordlist"

# history files
# Bash
export HISTFILE="${XDG_STATE_HOME:-$HOME/.local/state}/bash/history"
export HISTIGNORE="man:cat:less:vi:pss:psi:yss:ysi:cl:cll:clc:fcc:cdd:op:opp:xx:df:du:brtt:batt:mute:vol:iv:mm:torr:wttr:cu:cn:yt:yta"
#Zsh
export HISTFILE="${XDG_DATA_HOME:-$HOME/.local/share}/zsh/histfile"
export HISTORY_IGNORE="man:cat:less:vi:pss:psi:yss:ysi:cl:cll:clc:fcc:cdd:op:opp:xx:df:du:brtt:batt:mute:vol:iv:mm:torr:wttr:cu:cn:yt:yta"
# less, calc
export CALCHISTFILE="${XDG_CACHE_HOME:-$HOME/.cache}/calc_history"
export LESSHISTFILE="${XDG_DATA_HOME:-$HOME/.local/share}/lesshst"

# X11
export XAUTHORITY=/tmp/Xauthority
export XINITRC="${XDG_CONFIG_HOME:-$HOME/.config}/X11/xinitrc"
export ICEAUTHORITY="${XDG_CACHE_HOME:-$HOME/.cache}/ICEauthority"

# TeX
export TEXMFHOME="${XDG_DATA_HOME:-$HOME/.local/share}/texmf"
export TEXMFVAR="${XDG_CACHE_HOME:-$HOME/.cache}/texlive/texmf-var"
export TEXMFCONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/texlive/texmf-config"

# ncurses
export TERMINFO="${XDG_DATA_HOME:-$HOME/.local/share}/terminfo"
export TERMINFO_DIRS="${XDG_DATA_HOME:-$HOME/.local/share}/terminfo":/usr/share/terminfo

# SQLite
export SQLITERC="${XDG_CONFIG_HOME:-$HOME/.config}/sqlite3/sqliterc"
export SQLITE_HISTORY="${XDG_STATE_HOME:-$HOME/.local/state}/sqlite_history"

# MySQL
export MYSQL_HISTFILE="${XDG_DATA_HOME:-$HOME/.local/share}/mysql_history"

# pass
export PASSWORD_STORE_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/pass"
export PASSWORD_STORE_GENERATED_LENGTH=18

# gpg-agent as ssh manager
present_tty="$(/usr/bin/tty)"
ssh_agent_socket="$(/usr/bin/gpgconf --list-dirs agent-ssh-socket)"
export GPG_TTY="$present_tty"
/usr/bin/gpg-connect-agent --quiet updatestartuptty /bye >/dev/null
unset SSH_AGENT_PID
if [ "${gnupg_SSH_AUTH_SOCK_by:-0}" -ne $$ ]; then
    export SSH_AUTH_SOCK="$ssh_agent_socket"
fi

# R
export R_HOME_USER="${XDG_CONFIG_HOME:-$HOME/.config}/R"
export R_PROFILE_USER="${XDG_CONFIG_HOME:-$HOME/.config}/R/profile"
export R_HISTFILE="${XDG_CONFIG_HOME:-$HOME/.config}/R/history"
export R_LIBS_USER="${XDG_DATA_HOME:-$HOME/.local/share}/R"

# Julia
export JULIA_DEPOT_PATH="${XDG_DATA_HOME:-$HOME/.local/share}/julia:$JULIA_DEPOT_PATH"
export JULIAUP_DEPOT_PATH="${XDG_DATA_HOME:-$HOME/.local/share}/julia"

# fzf defaults
export FZF_DEFAULT_OPTS="--cycle --height 10%"

# define Home for any web browser
export WWW_HOME="https://duckduckgo.com"

# docker config
export DOCKER_CONFIG="${XDG_CONFIG_HOME:-$HOME/.config/}/docker"

# colored Man
export MANPAGER="/usr/bin/less -R --use-color -Dd+r -Du+g"
export MANROFFOPT="-P -c"

# minetest/luanti
export MINETEST_USER_PATH="${XDG_DATA_HOME:-$HOME/.local/share}/luanti"

# Go
export GOPATH="${XDG_DATA_HOME:-$HOME/.local/share}/go"
export GOMODCACHE="${XDG_CACHE_HOME:-$HOME/.cache}/go/mod"

# Rust
export CARGO_HOME="${XDG_DATA_HOME:-$HOME/.local/share}/cargo"
export RUSTUP_HOME="${XDG_DATA_HOME:-$HOME/.local/share}/rustup"

# Python
# python-setuptools
export PYTHON_EGG_CACHE="${XDG_CACHE_HOME:-$HOME/.cache}/python-eggs"
# python_history
export PYTHON_HISTORY="${XDG_STATE_HOME:-$HOME/.local/state}/python_history"
export PYTHONCACHEPREFIX="${XDG_CACHE_HOME:-$HOME/.cache}/python"
export PYTHONUSERBASE="${XDG_DATA_HOME:-$HOME/.local/share}/python"
# Jupyter notebook
# if [ "$(/usr/bin/pacman -Qs python-jupyter-core | \
    # /usr/bin/head -n1 | \
    # /usr/bin/cut -d ' ' -f2 | \
    # /usr/bin/cut -d '-' -f1 | \
    # /usr/bin/tr -d '\.')" -lt 500 ]; then
# same as above
if [ "$(/usr/bin/pacman -Qs python-jupyter-core | \
    /usr/bin/sed '2d;s/^.*\ //;s/\(^.*\)-.*$/\1/;s/\.//g')" -lt 500 ]; then
   export JUPYTER_CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/jupyter" 
else
   export JUPYTER_PLATFORM_DIRS="1"
fi

# npm
export NPM_CONFIG_USERCONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/npm/npmrc"

# Java
export _JAVA_OPTIONS=-Djava.util.prefs.userRoot="${XDG_CONFIG_HOME:-$HOME/.config}/java"

# Append to $PATH
export PATH="${PATH}:$HOME/.local/bin:$HOME/.local/bin/statusbar:$HOME/.local/bin/edirect:$CARGO_HOME/bin"
