#!/bin/sh
# ~/.config/X11/xinitrc
# after, export XINITRC="$XDG_CONFIG_HOME"/X11/xinitrc, in .zshrc or .bashrc

. /etc/X11/xinit/xinitrc.d/50-systemd-user.sh
/usr/bin/touch /tmp/Xauthority
#/usr/bin/xauth -q -f /tmp/Xauthority &
"$HOME"/.local/bin/xinfo &
/usr/bin/xrdb -load "$XDG_CONFIG_HOME"/X11/xresources &
"$HOME"/.local/bin/bright &
"$XDG_CONFIG_HOME"/xwallpaper/swall &
/usr/bin/xset r 200 50 &
/usr/bin/unclutter &
/usr/bin/picom 2>> ~/.local/share/picom.log &
/usr/bin/emacs --daemon &
/usr/bin/sxhkd -m -1 2>> ~/.local/share/sxhkd.log &
/usr/local/bin/dwmblocks 2>> ~/.local/share/dwmblocks.log &
exec /usr/local/bin/st 2>> ~/.local/share/st.log &
#/usr/bin/emacsclient -c -a "" &

exec "$HOME"/.local/bin/dwmstart
