#!/bin/bash
# ~/.config/bash/bashrc
# 
# If not running interactively, don't do anything
[[ $- != *i* ]] && return

[[ $DISPLAY ]] && shopt -s checkwinsize

PS1='[\u@\h \W]\$ '

# shellcheck disable=1090
for f in "${XDG_CONFIG_HOME:-$HOME/.config}"/shell/*; do source "$f"; done

# fzf keybindings and completion for bash
eval "$(fzf --bash)"

# find out if bash-completion is present, so as to enable for doas
if complete -p | /usr/bin/grep -q 'complete -F'; then
    complete -cf doas
else
    complete -F _command doas
fi
