enable_damage = true
creative_mode = false
mainmenu_last_selected_world = 3
menu_last_game = minetest
performance_tradeoffs = true
screen_h = 1047
screen_w = 1918
show_technical_names = true
world_config_selected_mod = 21
wieldview_node_tiles = false
wieldview_update_time = 2
unified_inventory_hide_disabled_buttons = true
mobs_npc_peaceful_igor = true
show_advanced = true
aux1_descends = true
maintab_LAST = local
video_driver = opengl3
enable_mapgen_debug_info = true
food_fuel = true
refinery_output = true
enable_local_map_saving = true
enable_fence_tall = true
doc_items_show_itemstrings = true
screenshot_path = /home/ts/mdi/pix/ss/
opengl_debug = true
orienteering_hud_alignment = left
fast_move = true
inventory_items_animations = true
refill_from_baskets = true
tooltip_append_itemname = true
mob_pathfinding_algorithm = Dijkstra
enable_server = false
port = 30000
name = op55
server_announce = false
server_name = ts-server
enable_esc_dialog = false
log_non_player_actions = true
bed_show_sleep_msg = true
cave_exploring_deaf_amateur = true
time_to_sleep = 0.75
foodblocks_drop_selves = true
itemframes.return_item = true
itemframes.log_actions = true
show_wielded_item_itemname = true
simple_oreminer.max_radius = 3
river_source_sounds = true
bones_position_message = true
